### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pklaschka** [pklaschka/chat-xd-plugin#139]
## Before
- [x] Create the intro video #130 

## On the day
- [x] Add privacy policy section on website
- [x] Add plugin homepage to menu on website
- [x] Turn repository public
- [x] Release on https://console.adobe.io
- [x] Release YouTube intro video
- [x] Create ProductHunt Post
- [x] Release blog post
- [x] Tweet

**Comment by pklaschka** [comment]
6. 19:00:00 UTC+2: YouTube video becomes public (automatically, scheduled in YouTube video manager)

**Comment by pklaschka** [comment]
7. LinkedIn Post (not planned in advance, but still 🙂 ): https://www.linkedin.com/feed/update/urn:li:activity:6724004911543070720/

**Comment by pklaschka** [comment]
8. 19:34:00 UTC+2: ProductHunt Post: https://www.producthunt.com/posts/document-chat-for-adobe-xd
